### ISSUE TITLE
Collaboration with Kyclos?

### ISSUE THREAD

**Issue by lanodan** [molan-git/harbour-tooter-b#20]
Hi,
I'm the main developer of Kyclos ( https://git.pleroma.social/pleroma/harbour-kyclos ), a fork of Tooter for good support of Pleroma (and now also Mastodon).
I'm not so sure what's your stance towards our project but I think it would be nice to be in one repository instead, I try to cherry-pick some of your changes so efforts aren't duplicated but would be better for both projects.

**Comment by molan-git** [comment]
HI lanodan, 
Thanks a lot for your message - great to hear that! Sorry for the late reply, I haven't have time to check the repo. I will have a look at your project and contact you asap.
