### ISSUE TITLE
Unable to install on SailfishOS 3.2.1

### ISSUE THREAD

**Issue by likeadragonmaid** [molan-git/harbour-tooter-b#52]
I am unable to install the app on sfos. It reports that libstdc++.so.6 is missing.

**Comment by molan-git** [comment]
Thanks for the report. 

Also this on Sailfish OS below version 3.3:
`Nothing provides libmpc.so.2 needed by gcc-5.2-5.2.0-1.armv7hl`

**Comment by molan-git** [comment]
@shoukolate The install fails are likely due to updated libraries in Sailfish OS 3.3. I might have to build the app with the older SDK in order to make it work on older Sailfish OS releases.

**Comment by molan-git** [comment]
should be fixed in version 1.0.6

**Comment by likeadragonmaid** [comment]
It works now, thank you very much for fixing it.
